[![imagenes](imagenes/pythonista.png)](https://pythonista.io)

## Aritmética y operadores con arreglos.

Los arreglos de Numpy son compatibles con los diversos operadores artiméticos y lógicos de Python.

En el caso de que se trate de un número o de otro arreglo cuyas dimensiones se ajusten correctamente, las operaciones aritméticas y lógicas se distribuirán a todos los elementos del arreglo definidos mediante *broadcasting*.

**Ejemplos:**

In [2]:
import numpy as np

Se creará la siguiente matriz.

In [3]:
matriz_1 = np.array([[1, 2, 3],
                  [4, 0, -5],
                  [-6, -7, -8]]) 

Todas las operaciones siguientes serán aplicadas a todos y cada uno de los elementos del arreglo.

In [4]:
matriz_1 + 100

array([[101, 102, 103],
       [104, 100,  95],
       [ 94,  93,  92]])

En este caso, la operación sólo se realizará en el tercer elemento.

In [5]:
matriz_1[2] * 3

array([-18, -21, -24])

El operador de división funciona de manera similar.

In [6]:
3 / matriz_1

/home/oi/pythonista/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 3.        ,  1.5       ,  1.        ],
       [ 0.75      ,         inf, -0.6       ],
       [-0.5       , -0.42857143, -0.375     ]])

In [7]:
matriz_1 / 3.42

array([[ 0.29239766,  0.58479532,  0.87719298],
       [ 1.16959064,  0.        , -1.4619883 ],
       [-1.75438596, -2.04678363, -2.33918129]])

Incluso los operadores lógicos se ejecutan por *broadcasting*.

In [8]:
matriz_1 > 1

array([[False,  True,  True],
       [ True, False, False],
       [False, False, False]])

Ahora se crearán dos nuevas matrices y se utilzarán algunos operadores sobre *matriz_1*.

In [10]:
matriz_2 = np.array([1, 2, 3])

In [11]:
matriz_2

array([1, 2, 3])

In [12]:
matriz_3 = np.array([[2], [4], [6]])

In [13]:
matriz_3

array([[2],
       [4],
       [6]])

En el siguiente caso, la operación se realizará en cada renglón de *matriz_1*.

In [14]:
matriz_1 * matriz_2

array([[  1,   4,   9],
       [  4,   0, -15],
       [ -6, -14, -24]])

En el siguiente caso, la operación se realizará en cada columna de *matriz_1*.

In [15]:
matriz_3 * matriz_1

array([[  2,   4,   6],
       [ 16,   0, -20],
       [-36, -42, -48]])

En el siguiente caso, se utilizarán matrices de dimensiones indénticas, de tal forma que cada elemento de la matriz es multiplicado con el elemento ubicado en la misma  posición de la otra.

In [16]:
np.array([[ 1,  2,  3],
       [ 4,  0, -5],
       [-6, -7, -8]]) * np.array([[ -1,  12,  13],
                              [ -4,  0, 5],
                              [6, 7, 8]])

array([[ -1,  24,  39],
       [-16,   0, -25],
       [-36, -49, -64]])

## Algunos atributos y métodos para la gestión de arreglos.

### El atributo *shape*.

Este atributo contiene las dimensiones y medidas de un objeto.

**Ejemplos:**

In [ ]:
np.array([1, 2, 3, 4]).shape

In [ ]:
np.array([[1, 2], [3, 4]]).shape

In [ ]:
np.array([[1], [2], [3], [4]]).shape

### El método *reshape()*.

Este método regresa un arreglo con las nuevas dimensiones definidas como parámetros. Las nuevas dimensiones deben de coincidir con el numero total de elementos del arreglo de origen.

La función *np.reshape()* es la implementación de este método.

**Ejemplos:**

In [1]:
matriz = np.array([[1, 2, 3],
                  [4, 0, -5],
                  [-6, -7, -8]])

NameError: name 'np' is not defined

In [ ]:
matriz.shape

In [ ]:
matriz.reshape(1, 1, 1, 1, 3,1,3)

In [ ]:
np.reshape(matriz,(1, 9))

### El atributo *flat*.

Este atributo es un objeto iterador (*np.flatirer*) capaz de regresar cada uno de los valores que contiene un arreglo.

**Ejemplo:**

In [ ]:
[x for x in matriz.flat]

In [ ]:
type(matriz.flat)

### El método *ravel()*.
Este atributo regresa un arreglo de una dimensión que contiene la referencia a cada uno de los valores que contiene el arreglo original.

La función *np.ravel()* es la impementación de este método.

### El método *flatten()*.

Este método regresa un arreglo de una dimensión que contiene cada uno de los valores que contiene el arreglo original, pero es independiente de este.

**Ejemplos:**
* Se creará el arreglo *matriz*.
* Se creará el arreglo *plana_copia* mendiante el método *flattten()* de *matriz*.
* Se creará el arreglo *plana_referencia* mendiante el método *ravel()* de *matriz*.
* Se modificará el contenido de *matriz*.

In [ ]:
matriz = np.array([[1, 2, 3],
                   [4, 0, -5],
                   [-6, -7, -8]])

In [ ]:
plana_copia = matriz.flatten()

In [ ]:
plana_copia

In [ ]:
plana_referencia = matriz.ravel()

In [ ]:
plana_referencia

In [ ]:
np.ravel(matriz)

In [ ]:
matriz[1, 1] = 1000

In [ ]:
matriz

In [ ]:
plana_copia

In [ ]:
plana_referencia

### El método *transpose()*.

Regresará el arreglo transpuesto del original.

La función *np.transpose()* es una implementación de ese método.

**Ejemplo:**

Se creará el arreglo transpuesto de el arreglo *matriz*.

In [ ]:
matriz = np.array([[1, 2, 3],
                   [4, 0, -5],
                   [-6, -7, -8]])

In [ ]:
matriz.transpose()

In [ ]:
np.transpose(matriz)

## Algunas funciones para la gestión de arreglos.

### La función *np.arange()*.

Crea un arreglo de una dimensión que contiene los enteros definidos en un rango al estilo de *xrange()*.

Es común utilizar esta función con el método *arrange()* para crear arreglos que contienen sucesiones numéricas.

**Ejemplos:**

In [ ]:
np.arange(5, 12)

In [ ]:
np.arange(9).reshape(3,3)

In [ ]:
np.arange(1, 13).reshape(2,3,2)

### La función *rollaxis()*.

Regresará un arreglo cuyos ejes, indicados como argumentos numéricos, comenzando desde el 0, serán invertidos. 

**Ejemplos:**

In [ ]:
arreglo = np.arange(27).reshape(3,3,3)

In [ ]:
arreglo

In [ ]:
np.rollaxis(arreglo, 1)

In [ ]:
np.rollaxis(arreglo, 2)

### La función *np.broadcast()*.

Esta función emula las operaciones de *broadcasting*. Da por resultado un objeto iterador que contiene las tuplas que describen el proceso de *broadcasting*.

### La función *np.broadcast_arrays()*.

Esta función regresa un objeto tipo *list* que contiene al arreglo afectado y al arreglo resultante.

### La función *np.broadcast_to()*.

Esta función aplica un *broadcasting* con el dato o arreglo que se ingresa como primer argumento a un arreglo nuevo cuyas dimensiones se corresonden a una objeto *tuple* que se ingresa como segundo argumento. 

**Ejemplos:**

* Se creará el arreglo *arreglo* de dimensiones (4, 3).
* Se ejecutará la función *np.broadcast()* al segundo elemento de la primera dimensión de *arreglo* aplicando el número 12.

In [ ]:
arreglo = np.arange(12).reshape(4, 3)

In [ ]:
arreglo

In [ ]:
resultante = np.broadcast(arreglo[2], 12)

In [ ]:
type(resultante)

In [ ]:
for item in resultante:
    print(item)

* Se ejecutará la función *np.broadcast()*  a todo el arreglo llamado *arreglo* aplicando un arreglo de dimensiones (3).

In [ ]:
[item for item in np.broadcast(arreglo, np.array([100, 200, 300]))]

In [ ]:
np.broadcast_arrays(arreglo, np.array([100, 200, 300]))

* Se ejecutará la función *np.broadcast_to* creando un nuevo arreglo de dimensiones (3,2,2) aplicando un arreglo de dimensiones (2).

In [ ]:
np.broadcast_to(12, (3,2))

### La función *np.expand_dims()*.
Esta función añadirá al arreglo ingresado como primer argumento el número de dimensiones indicadas como segundo argumento. El tamaño de cada dimensión será ajustado para ser compatible.

**Ejemplos:**

* Se creará un arreglo de dimensiones (2, 2).
* Se realizarán varias operaciones con *np.expand_dims()*.

In [ ]:
arreglo = np.arange(4).reshape(2, 2)

In [ ]:
arreglo

In [ ]:
np.expand_dims(arreglo, 1).shape

In [ ]:
np.expand_dims(arreglo, 2).shape

### La función *np.squeeze()*.
Esta función eliminará una dimensión al arreglo ingresado como  argumento.

**Ejemplo:**
* Se creará un arreglo llamado *arreglo* de dimensiones (1,3,3).
* Se ejecutará la función *np.squeeze()* en *arreglo*. 

In [ ]:
arreglo = np.arange(9).reshape(1,3,3)

In [ ]:
arreglo

In [ ]:
arreglo.shape

In [ ]:
arreglo = arreglo.reshape(1,1,9)

In [ ]:
np.squeeze(arreglo, 1)

In [ ]:
np.squeeze(arreglo).shape

### La función *np.concatenate()*.

Une una secuencia de arreglos contenidos dentro de un objeto *tuple* a un eje existente, se puede indicar el eje en el que se realizará la operación ingresando su número correspondiente como segundo argumento. 

**Ejemplo:**
*Se crearan 2 arreglos y se concatenarán en los ejes 1 y 0.

In [ ]:
arreglo_1 = np.array([[1, 2],
                      [3, 4]])

In [ ]:
arreglo_1

In [ ]:
arreglo_2 = np.array([[5, 6],
                      [7, 8]])

In [ ]:
arreglo_2

In [ ]:
np.concatenate((arreglo_1, arreglo_2), 1)

In [ ]:
np.concatenate((arreglo_1, arreglo_2), 0)

## La función *np.resize()*.

Esta función crea un nuevo arreglo a partir del que se ingresa como primer argumento. El nuevo arreglo tendrá las dimensiones ingresadas dentro de un objeto de tipo *tuple* como segundo argumento. 

En caso de que el nuevo arreglo contenga menos elementos, sólo se añadirán los primeros datos.

En caso de que el nuevo arreglo contenga m;as elementos, sólo se añadirán los primeros datos.

**Ejemplos:**

In [ ]:
arreglo = np.array([[1, 2],
                      [3, 4]])

In [ ]:
arreglo.shape

In [ ]:
np.resize(arreglo, (2,3))

In [ ]:
np.resize(arreglo,(2))

## Función *np.append*.

In [ ]:
arreglo = np.arange(9).reshape(1,3,3)

In [ ]:
arreglo

In [ ]:
np.append(arreglo, [np.array([[5, 6, 7],[8, 9, 10]])])

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2018.</p>