[![imagenes](imagenes/pythonista.png)](https://pythonista.io)

## Numpy.

[Numpy](http://www.numpy.org/) es un paquete que contiene una serie de tipos, clases y funciones especializadas en:

* Números muy pequeños o muy grandes.
* Matrices y arreglos.
* Algebra lineal.

Por comodidad es común importar el paquete *numpy* asignándole el nombre *np*.

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



## Los arreglos en Numpy.

Quizás el elemento más importante de Numpy son los arreglos, los cuales son colecciones ordenadas que contienen datos del mismo tipo. Los tipos de datos definidos.

Un arreglo se define generalmente mediante la siguiente sintaxis:

``` python
np.array(<tupla que contiene el arreglo>, dtype=<tipo>)
```

Para acceder a un elemento del arreglo se puede utilizar el método de indexado propio de los tipos *list* y *tuple* o usando la siguiente sintaxis:

``` python
<arreglo>[<índice_1>, <índice_2>,... <índice_n>]
```


**Ejemplo:**
A continuación se definirá un arreglo de 2x2 con tipos de datos enteros de 8 bits.

In [5]:
np.array(((1,2),(3,4)), dtype=np.int8)

array([[1, 2],
       [3, 4]], dtype=int8)

In [6]:
np.array(((1,2),(3,4)), dtype=np.int8)[0]

array([1, 2], dtype=int8)

In [7]:
np.array(((1,2),(3,4)), dtype=np.int8)[0][1]

2

In [8]:
np.array(((1,2),(3,4)), dtype=np.int8)[0, 1]

2

In [20]:
arreglo = np.array((((1,2),(3,4)),((5,6),(7,8))))

In [29]:
tupla = (((1,2),(3,4)),((5,6),(7,8)))

In [21]:
arreglo

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
len(arreglo)

2

In [15]:
arreglo[1]

array([[5, 6],
       [7, 8]])

In [16]:
arreglo[1][0]

array([5, 6])

In [18]:
type(arreglo[1][0][1])

numpy.int64

In [33]:
for item in arreglo:
    print(item, '\n', type(item))
    print()

[[1 2]
 [3 4]] 
 <class 'numpy.ndarray'>

[[5 6]
 [7 8]] 
 <class 'numpy.ndarray'>



In [27]:
for el_1, el_2 in arreglo:
    print(el_1, '\n', type(el_1))
    print(el_2, '\n', type(el_2))
    print()

[1 2] 
 <class 'numpy.ndarray'>
[3 4] 
 <class 'numpy.ndarray'>

[5 6] 
 <class 'numpy.ndarray'>
[7 8] 
 <class 'numpy.ndarray'>



In [41]:
np.array(((2, 3, 4),(6,7, 8)))

array([[2, 3, 4],
       [6, 7, 8]])

## Tipos de datos de Numpy.

Numpy define tipos de datos que extienden a los tipos con los que cuenta  Python.

Estos tipos de datos pueden tener diversos tamaños dependiendo del número de bits asignado para almacenar dichos tipos.

## Tipos enteros.

Es posible definir enteros de distintos tamaños como *int*, *int8*, *int16*, *int32* e *int64*, los cuales pueden ser positivos o negativos.

Es posible definir enteros sin signo, tales como *uint*, *uint8*, *uint16*, *uint32* e *uint64*.

Es posible definir un arreglo conformado por bytes mediante los tipos *byte*.

Si no se define el tipo de dato, Python utilizará *int64* por defecto.

**Ejemplos:**

In [42]:
np.array(((1, 2), (3, 4)))

array([[1, 2],
       [3, 4]])

In [43]:
type(np.array(((1, 2), (3, 4)))[0][1])

numpy.int64

In [44]:
np.array(((-1, 2), (3, 4)), dtype = np.uint8)

array([[255,   2],
       [  3,   4]], dtype=uint8)

In [45]:
np.array(((-1, 2), (3, 4)), dtype = np.uint64)

array([[18446744073709551615,                    2],
       [                   3,                    4]], dtype=uint64)

In [56]:
np.array(((101,11), (101, 11)), dtype = np.byte)

array([[101,  11],
       [101,  11]], dtype=int8)

### Tipos de punto flotante.

Los tipos de punto flotante siempre tendrán un signo y son *float* *float16*, *float32*, *float64*, *float128*. 

Si no se define, Python utilizará *float64*.

**Ejemplos:**

In [57]:
np.array(((11., 2), (15, 43)))

array([[11.,  2.],
       [15., 43.]])

In [58]:
type(np.array(((11., 2), (15, 43)))[0,0])

numpy.float64

### Tipos booleanos.
Se incluye el tipo *bool_* para indicar que el arreglo se trata de booleanos.

**Ejemplo:**

In [61]:
np.array(((1,'Hola'), (False, 0)), dtype = np.bool_)

array([[ True,  True],
       [False, False]])

### Tipos de texto.

Pueden ser de tipo *string_* o *unicode_* o *bytes_* el tamaño de los elementos del arreglo corresponderán al elemento de texto más extenso.

A diferencia de Python 3, *numpy* aún diferencia los tipos *string* y *unicode*.

Es posible definir el tamaño de los elementos por defecto utilizando la siguiente sintaxis al ingresar el argumento de *dtype*, siendo S para str y U para unicode:

``` python

dtype="<S<entero>"
dtype="<U<entero>"
```

**Ejemplos:**

In [62]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']))

array([['Hugo', 'Paco'],
       ['Luis Ignacio', 'Donald']], dtype='<U12')

In [63]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.unicode_)

array([['Hugo', 'Paco'],
       ['Luis Ignacio', 'Donald']], dtype='<U12')

In [64]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.bytes_)

array([[b'Hugo', b'Paco'],
       [b'Luis Ignacio', b'Donald']], dtype='|S12')

In [67]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.string_)

array([[b'Hugo', b'Paco'],
       [b'Luis Ignacio', b'Donald']], dtype='|S12')

In [68]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = ">U6")

array([['Hugo', 'Paco'],
       ['Luis I', 'Donald']], dtype='>U6')

## Valores numéricos especiales.

Numpy es capaz de reconocer números indeterminados e infintios.

### El valor *nan*.

Numpy utiliza *nan* cuando el valor no se trata de un número o es una indeterminación.

### El valor *inf*.

El valor *inf* representa un número tan grande que no puede ser calculado o el infinito*. Dicho valor puede llevar signo.

**Ejemplos:**

In [69]:
numeros = np.array(([1, 0],[-1, 1]))

In [70]:
numeros

array([[ 1,  0],
       [-1,  1]])

In [71]:
numeros / 0

/home/oi/pythonista/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/oi/pythonista/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ inf,  nan],
       [-inf,  inf]])

In [72]:
np.array([[np.inf, np.nan],[1, 3]])

array([[inf, nan],
       [ 1.,  3.]])

In [96]:
np.array((18446744073709551615000000000000000000000000000000000000000002., 2))[0]

1.8446744073709552e+61

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2018.</p>