[![imagenes](imagenes/pythonista.png)](https://pythonista.io)

## Indexado y rebanado de elementos en arreglos.

El indexado y rebanado de arreglos es similar al utilizado con los objetos tipo ```tuple``` o ```list``` y se utilizan los dos puntos ```:``` para indicar un rango de elementos para cada dimensión, las dimensiones están separadas por comas ```,```:

**Ejemplo práctico:**

Para realizar una obra de construcción se organizan dos frentes a los que se les asigna una brigada formada por 3 oficiales.
El siguiente arreglo indica la organización de las brigadas durante una semana de 5 días consecutivos empezando desde el lunes. 
Este arreglo es de 3 dimensiones de tamaño (5,2,3).

|BRIGADA| Lunes| Martes|Miércoles|Jueves|Viernes|
|:--:|:---:|:---:|:---:|:--:|:--:|
|1|Juan, Antonio, Ricardo|David, Julian, Ricardo|Arturo, Ricardo, Lucio|Alonso, Julian, Salvador|Lucio, Ramiro, Joaquín|
|2|Alonso, Jorge, Salvador|Arturo, Ramiro, Esteban|Jorge, Marco, Juan|Ricardo, Jorge, Esteban|Ricardo, Marco, Juan|



In [1]:
import numpy as np

In [ ]:
brigadas = np.array([[['Juan', 'Antonio', 'Ricardo'], ['Alonso', 'Jorge', 'Salvador']],
                    [['David', 'Julian', 'Ricardo'], ['Arturo', 'Ramiro', 'Esteban']],
                    [['Arturo', 'Ricardo', 'Lucio'], ['Jorge', 'Marco', 'Juan']],
                    [['Alonso', 'Julian', 'Salvador'], ['Ricardo', 'Jorge', 'Esteban']],
                    [['Lucio', 'Ramiro', 'Joaquín'], ['Ricardo', 'Marco', 'Juan']]])

In [ ]:
brigadas

Para conocer qué brigadas se formaron el martes y miércoles se hace lo siguiente:

In [ ]:
brigadas[1:3, :, :]

Para conocer cómo estaba formada la brigada en el segundo frente durante los días martes y miércoles se hace lo siguiente.

In [ ]:
brigadas[1:3,1,:]

In [ ]:
brigadas[1:3,1]

Para conocer los primeros 2 brigadistas del segundo frente durante toda la semana, se aplica lop siguiente:

In [ ]:
brigadas[:,1,0:2]

## Modificación de los elementos de un arreglo.
Para modificar un elemento se utiliza el índice y el operado de asignación (*=*).

**Ejemplos:**

Para modificar las 2 brigadas del viernes se hace lo siguiente:

In [2]:
brigadas = np.array([[['Juan', 'Antonio', 'Ricardo'], ['Alonso', 'Jorge', 'Salvador']],
                    [['David', 'Julian', 'Ricardo'], ['Arturo', 'Ramiro', 'Esteban']],
                    [['Arturo', 'Ricardo', 'Lucio'], ['Jorge', 'Marco', 'Juan']],
                    [['Alonso', 'Julian', 'Salvador'], ['Ricardo', 'Jorge', 'Esteban']],
                    [['Lucio', 'Ramiro', 'Joaquín'], ['Ricardo', 'Marco', 'Juan']]])

In [3]:
brigadas[4:] = [['Juan', 'Manuel', 'Julian'], 
               ['Ruben', 'Sergio', 'Pablo']]

In [4]:
brigadas

array([[['Juan', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['David', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramiro', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Juan', 'Manuel', 'Julian'],
        ['Ruben', 'Sergio', 'Pablo']]], dtype='<U8')

Para modificar a la segunda brigada del martes se realiza:

In [5]:
brigadas[1,1] = ['Lucio', 'Joaquín', 'Marco']

In [6]:
brigadas

array([[['Juan', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['David', 'Julian', 'Ricardo'],
        ['Lucio', 'Joaquín', 'Marco']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Juan', 'Manuel', 'Julian'],
        ['Ruben', 'Sergio', 'Pablo']]], dtype='<U8')

Para modificar a los primeros 2 oficiales de la primera brigada del miércoles se realiza:

In [7]:
brigadas[2,0,0:2] = ['Esteban', 'Salvador']

In [8]:
brigadas

array([[['Juan', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['David', 'Julian', 'Ricardo'],
        ['Lucio', 'Joaquín', 'Marco']],

       [['Esteban', 'Salvador', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Juan', 'Manuel', 'Julian'],
        ['Ruben', 'Sergio', 'Pablo']]], dtype='<U8')

## Indexación avanzada de arreglos.

Es posible identificar uno o más elementos de un arreglo mediante otro arreglo que identifique la posición de la primera dimensión del primero al que ???? se aplicarse mediante corchetes. Dicha posición será expresada como un entero positivo dentro del tamaño del arreglo.

**Ejemplos:**

In [9]:
brigadas = np.array([[['Juan', 'Antonio', 'Ricardo'], ['Alonso', 'Jorge', 'Salvador']],
                    [['David', 'Julian', 'Ricardo'], ['Arturo', 'Ramiro', 'Esteban']],
                    [['Arturo', 'Ricardo', 'Lucio'], ['Jorge', 'Marco', 'Juan']],
                    [['Alonso', 'Julian', 'Salvador'], ['Ricardo', 'Jorge', 'Esteban']],
                    [['Lucio', 'Ramiro', 'Joaquín'], ['Ricardo', 'Marco', 'Juan']]])

Se obtendrá un arreglo a partir de *brigadas* aplicando el arreglo *indice_1* que identifica a las cuadrillas de miércoles (2), lunes(0) y jueves(3).

In [10]:
indice_1 = np.array([2, 0, 3])

In [11]:
indice_1

array([2, 0, 3])

In [12]:
brigadas[indice_1]

array([[['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']],

       [['Juan', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']]], dtype='<U8')

Se creará un arreglo de 4 dimensiones. Una de ellas contiene a los elementos de jueves y lunes y la otra, de martes y viernes.

In [13]:
indice_2 = np.array([[3, 0], [1,4 ]])

In [14]:
indice_2

array([[3, 0],
       [1, 4]])

In [15]:
brigadas[indice_2]

array([[[['Alonso', 'Julian', 'Salvador'],
         ['Ricardo', 'Jorge', 'Esteban']],

        [['Juan', 'Antonio', 'Ricardo'],
         ['Alonso', 'Jorge', 'Salvador']]],


       [[['David', 'Julian', 'Ricardo'],
         ['Arturo', 'Ramiro', 'Esteban']],

        [['Lucio', 'Ramiro', 'Joaquín'],
         ['Ricardo', 'Marco', 'Juan']]]], dtype='<U8')

### Referencia con múltiples arreglos.

Si se ingresa una sucesión de arreglos separados por comas, el primer arreglo relacionará la primera dimensión del arreglo indexado, mientas que le siguiente a su vez, hará referencia a la segunda dimensión y así sucesivamente.

**Ejemplo:**

Se utilizarán 2 arreglos para obtener las brigadas correspondientes del arreglo *brigadas*.

In [16]:
brigadas = np.array([[['Juan', 'Antonio', 'Ricardo'], ['Alonso', 'Jorge', 'Salvador']],
                    [['David', 'Julian', 'Ricardo'], ['Arturo', 'Ramiro', 'Esteban']],
                    [['Arturo', 'Ricardo', 'Lucio'], ['Jorge', 'Marco', 'Juan']],
                    [['Alonso', 'Julian', 'Salvador'], ['Ricardo', 'Jorge', 'Esteban']],
                    [['Lucio', 'Ramiro', 'Joaquín'], ['Ricardo', 'Marco', 'Juan']]])

El primer arreglo definirá los elementos en la primera dimensión. En este caso, lunes (0) y jueves (3).

In [17]:
indice_x = np.array([0,3])

In [18]:
indice_x

array([0, 3])

El segundo arreglo definirá la primera brigada (0) y la segunda brigada(1).

In [19]:
indice_y = np.array([0,1])

In [20]:
indice_y

array([0, 1])

Al aplicarse ambos arreglos como índices, el resultado será un arreglo de dos dimensiones, incluyendo la primera brigada del lunes ([0, 0]) y la segunda brigada del jueves ([3, 1]).

In [21]:
brigadas[indice_x, indice_y]

array([['Juan', 'Antonio', 'Ricardo'],
       ['Ricardo', 'Jorge', 'Esteban']], dtype='<U8')

Si se añadiera un índice adicional, el resultado sería un arreglo de una dimesión.

In [ ]:
indice_z = np.array([0, 2])

In [ ]:
indice_z

In [ ]:
brigadas[indice_x, indice_y, indice_z]

**NOTA:** Es necesario que los arreglos que se utilizarán como índices, sean de las mismas dimensiones y tamaños.

## 'Broadcasting'.

Numpy permite llenar una región definida de un arreglo con un arreglo más pequeño, pero que se ajuste a las dimensiones del afectado.

**Ejemplos:**

En este caso, la seguna brigada del viernes será llenada con la cadena *'Juan'*.

In [ ]:
brigadas = np.array([[['Juan', 'Antonio', 'Ricardo'], ['Alonso', 'Jorge', 'Salvador']],
                    [['David', 'Julian', 'Ricardo'], ['Arturo', 'Ramiro', 'Esteban']],
                    [['Arturo', 'Ricardo', 'Lucio'], ['Jorge', 'Marco', 'Juan']],
                    [['Alonso', 'Julian', 'Salvador'], ['Ricardo', 'Jorge', 'Esteban']],
                    [['Lucio', 'Ramiro', 'Joaquín'], ['Ricardo', 'Marco', 'Juan']]])

In [ ]:
brigadas[4, 1] = 'Juan'

In [ ]:
brigadas

En este caso, todas las brigadas del miércoles serán *['Rocío', 'Martha', 'Angélica']*.

In [ ]:
brigadas = np.array([[['Juan', 'Antonio', 'Ricardo'], ['Alonso', 'Jorge', 'Salvador']],
                    [['David', 'Julian', 'Ricardo'], ['Arturo', 'Ramiro', 'Esteban']],
                    [['Arturo', 'Ricardo', 'Lucio'], ['Jorge', 'Marco', 'Juan']],
                    [['Alonso', 'Julian', 'Salvador'], ['Ricardo', 'Jorge', 'Esteban']],
                    [['Lucio', 'Ramiro', 'Joaquín'], ['Ricardo', 'Marco', 'Juan']]])

In [ ]:
brigadas[2] = np.array(['Rocio', 'Martha', 'Angélica'])

In [ ]:
brigadas

## Aritmética y operadores con arreglos.

Los arreglos de Numpy son compatibles con los diversos operadores artiméticos y lógicos de Python.

En el caso de que se trate de un número o de otro arreglo cuyas dimensiones se ajusten correctamente, las operaciones aritméticas y lógicas se distribuirán a todos los elementos del arreglo definidos mediante *broadcasting*.

**Ejemplos:**

* Se creará la siguiente matriz.

In [ ]:
matriz_1 = np.array([[1, 2, 3],
                  [4, 0, -5],
                  [-6, -7, -8]]) 

* Todas las operaciones siguientes serán aplicadas a todos y cada uno de los elementos del arreglo.

In [ ]:
matriz_1 + 100

* En este caso, la operación sólo se realizará en el tercer elemento.

In [ ]:
matriz_1[2] * 3

* El operador de división funciona de manera similar.

In [ ]:
3 / matriz_1

In [ ]:
matriz_1 / 3.42

* Incluso los operadores lógicos se ejecutan por *broadcasting*.

In [ ]:
matriz_1 > 1

* Ahora se crearán dos nuevas matrices y se utilzarán algunos operadores sobre *matriz_1*.
* Se crearán dos matrices de dimensiones *(3)*  y *(3, 1)*.

In [ ]:
matriz_2 = np.array([1, 2, 3])

In [ ]:
matriz_2

In [ ]:
matriz_3 = np.array([[2], [4], [6]])

In [ ]:
matriz_3

* En el siguiente caso, la operación se realizará en cada renglón de *matriz_1*.

In [ ]:
matriz_1 * matriz_2

* En el siguiente caso, la operación se realizará en cada columna de *matriz_1*.

In [ ]:
matriz_3 * matriz_1

* En el siguiente caso, se utilizarán matrices de dimensiones indénticas, de tal forma que cada elemento de la matriz es multiplicado con el elemento ubicado en la misma  posición de la otra.

In [ ]:
np.array([[ 1,  2,  3],
       [ 4,  0, -5],
       [-6, -7, -8]]) * np.array([[ -1,  12,  13],
                              [ -4,  0, 5],
                              [6, 7, 8]])

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2019.</p>