[![imagenes](imagenes/pythonista.png)](https://pythonista.io)

[*Numpy*](http://www.numpy.org/) es un paquete que contiene una biblioteca de recursos especializados en realizar operaciones optimizadas en arreglos de datos.

La instalación de *Numpy* puede ser hecha mediante *pip*.

In [1]:
!pip install numpy

You are using pip version 18.0, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


**Nota:** Por convención se sustituye el nombre del  módulo *numpy* por *np* al importarlo. En adelante, se utilizará dicha convención.

In [2]:
import numpy as np

## Los arreglos en *Numpy*.

Los elementos primordiales de *Numpy* son los arreglos (arrays), los cuales son colecciones ordenadas e indexables de datos.

* A diferencia de los tipos *list* y *tuple*, todos y cada uno de los datos contenidos en los arreglos de *Numpy* deben de ser de un tipo específico.

## Los objetos *np.ndarray*.

*Numpy* cuenta con una amplia variedad de funciones capaces de crear arreglos, pero todos ellos son de tipo *np.ndarray*.

Un arreglo genérico se define mediante la siguiente sintaxis:

``` python
np.array(<estructura del arreglo>, dtype=<tipo>)
```
* La estructura del arreglo se conforma por colecciones de datos indexables que pueden contener a su vez otras colecciones de datos indexables. 

* El parámetro *dtype* indica el tipo de los datos que contiene el arreglo. En caso de que no se defina el tipo de dato, *numpy*  tratará de definirlo.

**Ejemplo:**

A continuación se definirá un arreglo con las siguientes características:
* Esun arreglo de una dimensión que contiene tres elementos.
* Los elementos son enteros.
* No se define un tipo de dato con el parámetro *dtype*.
* Al arreglo se le asignará el nombre *arreglo*.

In [3]:
arreglo = np.array((1,2, 3))

In [4]:
arreglo

array([1, 2, 3])

In [5]:
type(arreglo)

numpy.ndarray

In [6]:
dir(arreglo)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

* A continuación se desplegará el tipo al que corresponde cada dato de *arreglo*.

In [7]:
for item in arreglo:
    print('valor: {}, tipo: {}'.format(item, type(item)))

valor: 1, tipo: <class 'numpy.int64'>
valor: 2, tipo: <class 'numpy.int64'>
valor: 3, tipo: <class 'numpy.int64'>


### Restricciones en los tipos de datos en un arreglo.

In [8]:
np.array(['d', 3 , (12, 6, True)])

ValueError: setting an array element with a sequence

## Dimensiones.

## Tipos de datos de Numpy.

Numpy define tipos de datos que extienden a los tipos con los que cuenta  Python.

Estos tipos de datos pueden tener diversos tamaños dependiendo del número de bits asignado para almacenar dichos tipos.

### Tipos enteros.

Es posible definir enteros de distintos tamaños como *int*, *int8*, *int16*, *int32* e *int64*, los cuales pueden ser positivos o negativos.

Es posible definir enteros sin signo, tales como *uint*, *uint8*, *uint16*, *uint32* e *uint64*.

Es posible definir un arreglo conformado por bytes mediante los tipos *byte*.

Si no se define el tipo de dato, Python utilizará *int64* por defecto.

**Ejemplos:**

In [9]:
np.array(((1, 2), (3, 4)))

array([[1, 2],
       [3, 4]])

In [10]:
type(np.array(((1, 2), (3, 4)))[0][1])

numpy.int64

In [11]:
np.array(((-1, 2), (3, 4)), dtype = np.uint8)

array([[255,   2],
       [  3,   4]], dtype=uint8)

In [12]:
np.array(((-1, 2), (3, 4)), dtype = np.uint64)

array([[18446744073709551615,                    2],
       [                   3,                    4]], dtype=uint64)

In [15]:
np.array(((101,11), (101, 256)), dtype = np.byte)

array([[101,  11],
       [101,   0]], dtype=int8)

### Tipos de punto flotante.

Los tipos de punto flotante siempre tendrán un signo y son *float* *float16*, *float32*, *float64*, *float128*. 

Si no se define, Python utilizará *float64*.

**Ejemplos:**

In [ ]:
np.array(((11., 2), (15, 43)))

In [ ]:
type(np.array(((11., 2), (15, 43)))[0,0])

### Tipos booleanos.
Se incluye el tipo *bool_* para indicar que el arreglo se trata de booleanos.

**Ejemplo:**

In [ ]:
np.array(((1,'Hola'), (False, 0)), dtype = np.bool_)

### Tipos de texto.

Pueden ser de tipo *string_* o *unicode_* o *bytes_* el tamaño de los elementos del arreglo corresponderán al elemento de texto más extenso.

A diferencia de Python 3, *numpy* aún diferencia los tipos *string* y *unicode*.

Es posible definir el tamaño de los elementos por defecto utilizando la siguiente sintaxis al ingresar el argumento de *dtype*, siendo S para str y U para unicode:

``` python

dtype="<S<entero>"
dtype="<U<entero>"
```

**Ejemplos:**

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']))

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.unicode_)

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.bytes_)

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.string_)

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = ">U6")

## Valores numéricos especiales.

Numpy es capaz de reconocer números indeterminados e infintios.

### El valor *nan*.

Numpy utiliza *nan* cuando el valor no se trata de un número o es una indeterminación.

### El valor *inf*.

El valor *inf* representa un número tan grande que no puede ser calculado o el infinito*. Dicho valor puede llevar signo.

**Ejemplos:**

In [ ]:
numeros = np.array(([1, 0],[-1, 1]))

In [ ]:
numeros

In [ ]:
numeros / 0

In [ ]:
np.array([[np.inf, np.nan],[1, 3]])

In [ ]:
np.array((18446744073709551615000000000000000000000000000000000000000002., 2))[0]

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2018.</p>