[![imagenes](imagenes/pythonista.png)](https://pythonista.io)

## Creación de arreglos.

Además de *np.array* es posible crear arreglos con ciertas características particulares.

### Creación de arreglos llenos de números 1.

Para crear un arreglo que contenga exclusivamente el número 1 en cada elemento se utiliza la función *np.ones()*.

``` python
np.ones(<tupla indicando el tamaño>, dtype)
```
En caso de no indicarse el tipo, se utilizará *float64*.

**Ejemplos:**

In [1]:
import numpy as np

In [2]:
np.ones((2, 5, 3, 6), dtype=np.bool_)

array([[[[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]]],


       [[[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  

In [3]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
type(np.ones((3,3))[1,1])

numpy.float64

### Creación de arreglos llenos de números 0.

Para crear un arreglo que contenga exclusivamente el número 0 en cada elemento se utiliza la función *np.zeros()*.

``` python
np.zeros(<tupla indicando el tamaño>, dtype)
```
En caso de no indicarse el tipo, se utilizará *float64*.

**Ejemplos:**

In [5]:
np.zeros((2,2,2), dtype=np.bool)

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
type(np.zeros((3,3))[1,1])

numpy.float64

### Creación de arreglos sin elementos definidos.

Para crear un arreglo sin elementos definidos cada elemento se utiliza la función *np.empty()* y *np.ndarray()*.

``` python
np.empty(<tupla indicando el tamaño>, dtype)
np.ndarray(<tupla indicando el tamaño>, dtype)
```
La función *np.empty()* es similar a *np.zeros()*, mientras que *np.ndarray()* contiene basura.

En caso de no indicarse el tipo, se utilizará *float64*.

**Ejemplos:**

In [8]:
np.empty((2,2,2), dtype=np.bool)

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [9]:
np.zeros((3,3), dtype=np.unicode_)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [10]:
type(np.empty((3,3))[1,1])

numpy.float64

In [11]:
np.ndarray((2,2))

array([[6.91056850e-310, 1.31831734e-316],
       [1.58101007e-322, 6.91056935e-310]])

In [12]:
np.ndarray((2,2), dtype='>U10')

array([['', ''],
       ['', '']], dtype='>U10')

### Creación de un arreglo aleatorio.

Numpy cuenta con el paquete *np.random*, el cual permite crear arreglos aleatorios de distintas índoles e incluso ajustándose a ciertas distribuciones probabilísitcas).

Para ilustrar el uso de dicho módulo se explorarán las siguientes funciones:

* La función *np.random.rand()* crea un arreglo cuyos elementos son aleatorios.
* La función *np.random.randn()* crea un arreglo cuyos elementos son aleatorios a partir de una distribución normal estándar.
* La función *np.random.randint()* crea un arreglo de números enteros aleatorios a partir de un límite inferior y uno superior.

Las sintaxis son las siguientes:

``` python
np.random.rand(<tamaño>)
np.random.randn(<tamaño>)
np.random.randint(<limite inferior>, <limite superior>, <tupla indicando el tamaño>)
```

**Ejemplos:**

In [ ]:
help(np.random)

In [14]:
np.random.rand(2,2)

array([[0.25763273, 0.19335349],
       [0.66409946, 0.12561012]])

In [15]:
np.random.randint(1,5,(3,3))

array([[4, 4, 4],
       [3, 3, 4],
       [3, 1, 4]])

In [16]:
np.random.randn(15,15)

array([[-0.36158415, -0.23596908,  0.52882867, -1.28969353, -0.84896928,
         1.30872094, -0.20271612, -0.00826881, -1.20599754,  0.56444867,
        -0.93037179,  0.23289594, -0.85172803,  1.32351197, -2.08683291],
       [ 1.44069043, -0.65352641, -1.57008106, -1.50403293, -1.4126041 ,
        -0.97822584, -0.12646068,  0.13079795, -0.72636232,  0.76555548,
         0.13297455, -1.44176888,  0.18739377, -1.91782788,  0.44984763],
       [ 1.27508165, -0.92726507, -1.71377353, -0.92450805,  0.32766564,
         0.11747776, -0.65581876,  1.52946144,  0.90817605, -0.04970863,
         1.34405395,  0.32935763,  0.30214144,  1.24765706,  0.59572463],
       [-0.81486823, -0.00814841, -2.33103938,  0.40896453,  0.27012062,
        -1.37803377,  0.81880825,  1.20036293, -0.38659482,  0.74969305,
        -0.68821919, -2.37344264,  0.83115201, -1.16907082,  0.34334446],
       [-0.03261264, -0.20062356, -0.62381908,  2.01883748, -1.53243929,
        -0.58139935,  1.83984476,  1.69998719, 

## Copiado de un arreglo.

Todos los arreglos cuentan con el método *copy()*, el cual permite crear una arreglo totalmente nuevo, evitando el efecto aliasing.

**Ejemplo:**

In [17]:
arreglo_1 = np.array(([1, 2], [3, 4]))

In [18]:
arreglo_1

array([[1, 2],
       [3, 4]])

In [19]:
arreglo_2 = arreglo_1.copy()

In [20]:
arreglo_2

array([[1, 2],
       [3, 4]])

In [21]:
arreglo_1 is arreglo_2

False

In [22]:
arreglo_1 == arreglo_2 

array([[ True,  True],
       [ True,  True]])

## Escritura y lectura de arreglos en el sistema de archivos.

### Escritura de arreglos.
Numpy cuenta con varias funciones para almacenar arreglos en el sistema de archivos local.

* *np.save()* permite guardar un arreglo en un archivo con extensión *.npy*.
* *np.savetxt()* permite guardar un arreglo en un archivo  de texto.
* *np.savez()* permite guardar varios arreglo en un archivo con extensión *.npz*.
* *np.savez_compressed()* permite guardar varios arreglos en un archivo con extensión *.npz* comprimido.

Las sintaxis son:

``` python
np.save('<ruta>' <arreglo>)
np.savetxt('<ruta>' <arreglo>, delimiter='<caracter delimitador>')
np.savez('<ruta>' <arreglo 1>, <arreglo 2>,... <arreglo n>)
np.savez_compressed('<ruta>' <arreglo 1>, <arreglo 2>,... <arreglo n>)
```


**Ejemplos:**

In [23]:
np.save('arreglo_1', arreglo_1)

In [24]:
%ls arreglo_1.npy

arreglo_1.npy


In [25]:
%cat arreglo_1.npy

�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2), }                                                          


In [26]:
np.savetxt('arreglo_1.txt', arreglo_1)

In [27]:
%cat arreglo_1.txt

1.000000000000000000e+00 2.000000000000000000e+00
3.000000000000000000e+00 4.000000000000000000e+00


In [29]:
np.savez('arreglos', arreglo_1, arreglo_2)

In [30]:
%ls arreglos.npz

arreglos.npz


In [31]:
%cat arreglos.npz

PK!�DK[��	arr_0.npy�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2), }                                                          
PK!�DK[��	arr_1.npy�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2), }                                                          
PK!�DK[��	�arr_0.npyPK!�DK[��	��arr_1.npyPKn�

### Lectura de arreglos.

Para leer archivos con arreglos se utilizan:

* *np.load()* permite leer arreglos a partir de un archivo con extensión *.npy* o *npz*.
* *np.loadtxt()* permite leer un arreglo en un archivo  de texto.
Las sintaxis son:

``` python
np.load('<ruta>')
np.loadtxt('<ruta>', delimiter='<caracter delimitador>')
```

**Ejemplos:**

In [36]:
np.load('arreglos.npz')

In [33]:
np.loadtxt('arreglo_1.txt')

array([[1., 2.],
       [3., 4.]])

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2018.</p>