[![imagenes/pythonista.png](imagenes/pythonista.png)](https://pythonista.io)

Numpy es el componente de Scipy que contiene las herramientas básicas de cálculo numérico, generación de números aleatorios, estadística básica, trigonometría, operaciones matriciales y a algebra lineal; entre otras, las cuales son utilizadas intensivamente por el resto de las bibliotecas.

Su propia biblioteca de recursos es muy extensa y cubre gran cantidad de herramientas.

A continuación se presentarán algunas de ellas.

## Rangos numéricos.

Numpyu incluye alguinas funciones que generan una sucesion de números en un rango específico. Una de estar funciones es ```np.arange()```. Sin embargo, existen otras como ```np.linstep()``` y ```np.logspace()```.

### La función ```np.linspace()```.

Esta función creará una secuencia de números dentro de un rango dado que corresponde segmentos, incluyendo el inicio y el final.

In [1]:
import numpy as np

In [2]:
np.linspace(0, 7)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ,
       2.14285714, 2.28571429, 2.42857143, 2.57142857, 2.71428571,
       2.85714286, 3.        , 3.14285714, 3.28571429, 3.42857143,
       3.57142857, 3.71428571, 3.85714286, 4.        , 4.14285714,
       4.28571429, 4.42857143, 4.57142857, 4.71428571, 4.85714286,
       5.        , 5.14285714, 5.28571429, 5.42857143, 5.57142857,
       5.71428571, 5.85714286, 6.        , 6.14285714, 6.28571429,
       6.42857143, 6.57142857, 6.71428571, 6.85714286, 7.        ])

In [3]:
np.linspace(0, 7, num=100)

array([0.        , 0.07070707, 0.14141414, 0.21212121, 0.28282828,
       0.35353535, 0.42424242, 0.49494949, 0.56565657, 0.63636364,
       0.70707071, 0.77777778, 0.84848485, 0.91919192, 0.98989899,
       1.06060606, 1.13131313, 1.2020202 , 1.27272727, 1.34343434,
       1.41414141, 1.48484848, 1.55555556, 1.62626263, 1.6969697 ,
       1.76767677, 1.83838384, 1.90909091, 1.97979798, 2.05050505,
       2.12121212, 2.19191919, 2.26262626, 2.33333333, 2.4040404 ,
       2.47474747, 2.54545455, 2.61616162, 2.68686869, 2.75757576,
       2.82828283, 2.8989899 , 2.96969697, 3.04040404, 3.11111111,
       3.18181818, 3.25252525, 3.32323232, 3.39393939, 3.46464646,
       3.53535354, 3.60606061, 3.67676768, 3.74747475, 3.81818182,
       3.88888889, 3.95959596, 4.03030303, 4.1010101 , 4.17171717,
       4.24242424, 4.31313131, 4.38383838, 4.45454545, 4.52525253,
       4.5959596 , 4.66666667, 4.73737374, 4.80808081, 4.87878788,
       4.94949495, 5.02020202, 5.09090909, 5.16161616, 5.23232

### La función ```np.logspace()```.

Esta función creará una secuencia de números en una sucesion logarítmica. La base por defecto es 10.

In [4]:
np.logspace(5, 7, num=10)

array([  100000.        ,   166810.05372001,   278255.94022071,
         464158.88336128,   774263.68268113,  1291549.66501488,
        2154434.69003188,  3593813.66380463,  5994842.50318941,
       10000000.        ])

## El paquete ```numpy.linalg```.

La biblioteca especialziada en operaciones de algebra lineal de *Numpy* es ```numpy.linalg```.

El estudio de todas las funciones contenodas en este paquete están fuera de los alcances de este curso, pero se ejemplificarán las funciones.

* ```numpy.linalg.det()```
* ```numpy.linalg.solve()```

In [5]:
import numpy.linalg

In [ ]:
help(numpy.linalg)

### Cálculo del determinate de una matriz mediante ```numpy.linalg.det()```.



**Ejemplo:**

* Se calculará el determinante de la matriz:

$$ \det\begin{vmatrix}0&1&2\\3&4&5\\6&7&8\end{vmatrix}$$

* El cálculo del determinante es el siguiente:

$$ ((0 * 4 * 8) + (1 * 5 * 6) + (2 * 3 * 7)) - ((6 * 4 * 2) + (7 * 5 * 0) + (8 * 3* 1)) = 0$$

In [7]:
matriz = np.arange(9).reshape(3, 3)

In [8]:
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
numpy.linalg.det(matriz)

0.0

* Se calculará el determinante de la matriz:

$$ \det\begin{vmatrix}1&1&2\\3&4&5\\6&7&8\end{vmatrix}$$

* El cálculo del determinante es el siguiente:

$$ ((1 * 4 * 8) + (1 * 5 * 6) + (2 * 3 * 7)) - ((6 * 4 * 2) + (7 * 5 * 1) + (8 * 3* 1)) = -3$$

In [10]:
matriz = np.array([[1, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])

In [11]:
numpy.linalg.det(matriz)

-2.999999999999999

### Soluciones de ecuaciones lineales con la función ```np.linalg.solve()```.

Un sistema de ecuaciones lineales coresponde un conjunto de ecuaciones de la forma:

$$
a_{11}x_1 + a_{12}x_2 + \cdots a_{1n}x_n = y_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots a_{2n}x_n = y_2\\
\vdots\\
a_{m1}x_1 + a_{m2}x_2 + \cdots a_{mn}x_n = y_m
$$

Lo cual puede ser expresado de forma matricial.

$$ 
\begin{bmatrix}a_{11}\\a_{21}\\ \vdots\\ a_{m1}\end{bmatrix}x_1 + \begin{bmatrix}a_{12}\\a_{22}\\ \vdots\\ a_{m2}\end{bmatrix}x_2 + \cdots \begin{bmatrix}a_{m1}\\a_{m2}\\ \vdots\\ a_{mn}\end{bmatrix}x_n = \begin{bmatrix}y_{1}\\y_{2}\\ \vdots\\ y_{m}\end{bmatrix}
$$

Existen múltiples métodos para calcular los valores $x_1, x_2 \cdots x_n$ que cumplan con el sistema siempre que $m = n$.

Numpy cuenta con la función *np.linalg.solve()*, la cual puede calcular la solución de un sistema de ecuaciones lineales al expresarse como un par de matrices de la siguiente foma:

$$ 
\begin{bmatrix}a_{11}&a_{12}&\cdots&a_{1n}\\a_{21}&a_{22}&\cdots&a_{2n}\\ \vdots\\ a_{n1}&a_{n2}&\cdots&a_{nn}\end{bmatrix}= \begin{bmatrix}y_{1}\\y_{2}\\ \vdots\\ y_{n}\end{bmatrix}
$$

La función ```numpy.linagl.solve()``` permite resolver sistemas de ecuaciones lineales ingresando un arreglo de dimensiones ```(n, n)``` como primer argumente y otro con dimensión ```(n)``` como segundo argumento. 

**Ejemplo:**

* Para resolver el sistema de ecuaciones:

$$
2x_1 + 5x_2 - 3x_3 = 22.2 \\
11x_1 - 4x_2 + 22x_3 = 11.6 \\
54x_1 + 1x_2 + 19x_3 = -40.1 \\
$$

* Se realiza lo siguiente:

In [12]:
a = np.array([[2, 5, -3],
              [11, -4, 22],
              [54, 1, 19]])

In [13]:
a.shape

(3, 3)

In [14]:
y = np.array([22.2, 11.6, -40.1])

In [15]:
y.shape

(3,)

In [16]:
np.linalg.solve(a, y)

array([-1.80243902,  6.7549776 ,  2.65666999])

In [18]:
arreglo_1 = np.array([[1, 2],
          [3, 4]])

In [19]:
arreglo_2 = np.array([[11, 12],
          [13, 14]])

## Producto punto entre dos matrices.

In [20]:
arreglo_1 @ arreglo_2

array([[37, 40],
       [85, 92]])

In [21]:
arreglo_1.dot(arreglo_2)

array([[37, 40],
       [85, 92]])

## Producto cruz entre dos matrices.

In [23]:
np.cross(arreglo_1, arreglo_2)

array([-10, -10])

In [26]:
arreglo_3 = np.arange(6).reshape(2, 3)

In [28]:
arreglo_4 = np.arange(7, 13).reshape(3, 2)

In [29]:
arreglo_3 @ arreglo_4 

array([[ 31,  34],
       [112, 124]])

In [30]:
arreglo_4 @ arreglo_3

array([[24, 39, 54],
       [30, 49, 68],
       [36, 59, 82]])

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2019.</p>