[![imagenes](imagenes/pythonista.png)](https://pythonista.io)

## Creación de arreglos.

Además de *np.array* es posible crear arreglos de ciertas índoles.

### Creación de arreglos llenos de números 1.

Para crear un arreglo que contenga exclusivamente el número 1 en cada elemento se utiliza la función *np.ones()*.

``` python
np.ones(<tupla indicando el tamaño>, dtype)
```
En caso de no indicarse el tipo, se utilizará *float64*.

**Ejemplos:**

In [1]:
import numpy as np

In [3]:
np.ones((2,5,3, 6), dtype=np.bool)

array([[[[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]]],


       [[[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  

In [4]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
type(np.ones((3,3))[1,1])

numpy.float64

### Creación de arreglos llenos de números 0.

Para crear un arreglo que contenga exclusivamente el número 0 en cada elemento se utiliza la función *np.zeros()*.

``` python
np.zeros(<tupla indicando el tamaño>, dtype)
```
En caso de no indicarse el tipo, se utilizará *float64*.

**Ejemplos:**

In [6]:
np.zeros((2,2,2), dtype=np.bool)

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
type(np.zeros((3,3))[1,1])

numpy.float64

### Creación de arreglos sin elementos definidos.

Para crear un arreglo sin elementos definidos cada elemento se utiliza la función *np.empty()* y *np.ndarray()*.

``` python
np.empty(<tupla indicando el tamaño>, dtype)
np.ndarray(<tupla indicando el tamaño>, dtype)
```
La función *np.empty()* es similar a *np.zeros()*, mientras que *np.ndarray()* contiene basura.

En caso de no indicarse el tipo, se utilizará *float64*.

**Ejemplos:**

In [9]:
np.empty((2,2,2), dtype=np.bool)

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [22]:
np.zeros((3,3), dtype=np.unicode_)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [13]:
type(np.empty((3,3))[1,1])

numpy.float64

In [14]:
np.ndarray((2,2))

array([[6.94817130e-310, 6.94817130e-310],
       [7.43608677e-246, 1.37409445e-231]])

In [15]:
np.ndarray((2,2), dtype='>U10')

array([['', ''],
       ['', '']], dtype='>U10')

### Creación de un arreglo aleatorio.

Numpy cuenta con el paquete *np.random*, el cual permite crear arreglos aleatorios de distintas índoles e incluso ajustándose a ciertas distribuciones probabilísitcas).

Para ilustrar el uso de dicho módulo se explorarán las siguientes funciones:

* La función *np.random.rand()* crea un arreglo cuyos elementos son aleatorios.
* La función *np.random.randn()* crea un arreglo cuyos elementos son aleatorios a partir de una distribución normal estándar.
* La función *np.random.randint()* crea un arreglo de números enteros aleatorios a partir de un límite inferior y uno superior.

Las sintaxis son las siguientes:

``` python
np.random.rand(<tamaño>)
np.random.randn(<tamaño>)
np.random.randint(<limite inferior>, <limite superior>, <tupla indicando el tamaño>)
```

**Ejemplos:**

In [23]:
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    ==================== =========================================================
    Utility functions
    random_sample        Uniformly distributed floats over ``[0, 1)``.
    random               Alias for `random_sample`.
    bytes                Uniformly distributed random bytes.
    random_integers      Uniformly distributed integers in a given range.
    permutation          Randomly permute a sequence / generate a random sequence.
    shuffle              Randomly permute a sequence in place.
    seed                 Seed the random number generator.
    choice               Random sample from 1-D array.
    
    ==================== =========================================================
    
    ==================== =========================================================
    Compatibility functions
    rand                 Uniformly distributed values.
    randn

In [24]:
np.random.rand(2,2)

array([[0.05012961, 0.13611807],
       [0.65147787, 0.1724003 ]])

In [25]:
np.random.randint(1,5,(3,3))

array([[1, 1, 3],
       [2, 1, 3],
       [2, 2, 4]])

In [26]:
np.random.randn(15,15)

array([[ 0.62903151, -2.65447747,  1.00588864,  0.45817177,  0.35964974,
         0.6958812 ,  0.79425593, -1.95304899, -1.63276127, -0.37780752,
         2.20841891,  3.21182257, -0.09908836,  1.37897088, -0.82381255],
       [-0.00518084, -1.28184198, -0.60858474, -0.99110218, -1.19816356,
        -0.2700044 , -0.87482756,  1.00133171,  0.32039537,  1.10171921,
         0.42285106,  0.07711986, -0.33997939, -0.21330877,  0.52347134],
       [-0.90903758, -0.44851841, -0.20828719, -0.45192539, -0.17526262,
        -0.51162235, -0.03901413,  0.65961875,  0.0815826 , -0.1831805 ,
        -0.43968964, -0.31220442,  0.09191337,  0.50780096,  1.42742106],
       [-1.17001706, -0.3585323 ,  0.14621704, -0.57780492,  2.35485785,
        -0.12371651,  0.48361457,  0.66481657, -1.14801341,  0.07029581,
        -0.0895563 , -0.69996661,  1.13275223, -0.15622327, -0.81651694],
       [ 0.47987974,  0.21215671,  0.27238764, -0.92941424, -0.84415942,
         0.75701901,  0.36370839,  0.16237371, 

## Copiado de un arreglo.

Todos los arreglos cuentan con el método *copy()*, el cual permite crear una arreglo totalmente nuevo, evitando el efecto aliasing.

**Ejemplo:**

In [27]:
arreglo_1 = np.array(([1, 2], [3, 4]))

In [28]:
arreglo_2 = arreglo_1.copy()

In [29]:
arreglo_1 is arreglo_2

False

In [30]:
arreglo_1 == arreglo_2 

array([[ True,  True],
       [ True,  True]])

## Escritura y lectura de arreglos en el sistema de archivos.

### Escritura de arreglos.
Numpy cuenta con varias funciones para almacenar arreglos en el sistema de archivos local.

* *np.save()* permite guardar un arreglo en un archivo con extensión *.npy*.
* *np.savetxt()* permite guardar un arreglo en un archivo  de texto.
* *np.savez()* permite guardar varios arreglo en un archivo con extensión *.npz*.
* *np.savez_compressed()* permite guardar varios arreglo en un archivo con extensión *.npz* comprimido.

Las sintaxis son:

``` python
np.save('<ruta>' <arreglo>)
np.savetxt('<ruta>' <arreglo>, delimiter='<caracter delimitador>')
np.savez('<ruta>' <arreglo 1>, <arreglo 2>,... <arreglo n>)
np.savez_compressed('<ruta>' <arreglo 1>, <arreglo 2>,... <arreglo n>)
```


**Ejemplos:**

In [31]:
np.save('arreglo_1', arreglo_1)

In [ ]:
%ls arreglo_1.npy

In [32]:
%cat arreglo_1.npy

�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2), }                                                          


In [35]:
np.savetxt('arreglo_1.txt', arreglo_1)

In [36]:
%cat arreglo_1.txt

1.000000000000000000e+00 2.000000000000000000e+00
3.000000000000000000e+00 4.000000000000000000e+00


In [41]:
np.savez_('arreglos', arreglo_1, arreglo_2)

In [42]:
%ls arreglos.npz

arreglos.npz


In [43]:
%cat arreglos.npz

PK!�DK[R�	arr_0.npy�����P�P���Z�\�n��n�i������_TR���_��
wK�)N�g$��F:
F�:
�
d.F`���P�JPK!�DK[R�	arr_1.npy�����P�P���Z�\�n��n�i������_TR���_��
wK�)N�g$��F:
F�:
�
d.F`���P�JPK!�DK[R�	�arr_0.npyPK!�DK[R�	�yarr_1.npyPKn�

### Lectura de arreglos.

Para leer archivos con arreglos se utilizan:

* *np.load()* permite leer arreglos a partir de un archivo con extensión *.npy* o *npz*.
* *np.savetxt()* permite leer un arreglo en un archivo  de texto.

Las sintaxis son:

``` python
np.load('<ruta>')
np.loadtxt('<ruta>', delimiter='<caracter delimitador>')
```

**Ejemplos:**

In [45]:
np.load('arreglos.npz')

In [46]:
np.loadtxt('arreglo_1.txt')

array([[1., 2.],
       [3., 4.]])

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2018.</p>