[![imagenes/pythonista.png](imagenes/pythonista.png)](https://pythonista.io)

# Gestión y análisis de datos.

In [6]:
import numpy as np

Debido a las características de los arreglos de *Numpy* para hacer "broadcasting", la biblioteca cuenta con una ampla gama de funciopnes que permiten aoplicarlas a cada uno de los objetos que contiene.

La lista de funciones es demasiado extensa como para enumerarlas todas, pero algunas de ellas son:


## Funciones trigonométricas.

* ```np.cos()```
* ```np.sin()```
* ```np.tan()```
* ```np.cosh()```
* ```np.sinh()```
* ```np.tanh()```
* ```np.arccos()```
* ```np.arcsin()```
* ```np.arctan()```
* ```np.arctan2()```
* ```np.arccosh()```
* ```np.arcsinh()```
* ```np.arctanh()```
* ```np.arctan2h()```
* ```np.hypot()```
* ```np.deg2rad()```
* ```np.degrees()```
* ```np.rad2deg()```
* ```np.radians()```

In [7]:
opuesto = np.ones((4,4))

In [8]:
opuesto

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
adyacente = np.ones((4,4))

In [10]:
adyacente

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
angulo = np.arctan2(opuesto, adyacente)

In [12]:
angulo

array([[0.78539816, 0.78539816, 0.78539816, 0.78539816],
       [0.78539816, 0.78539816, 0.78539816, 0.78539816],
       [0.78539816, 0.78539816, 0.78539816, 0.78539816],
       [0.78539816, 0.78539816, 0.78539816, 0.78539816]])

In [13]:
np.degrees(angulo)

array([[45., 45., 45., 45.],
       [45., 45., 45., 45.],
       [45., 45., 45., 45.],
       [45., 45., 45., 45.]])

## Funciones da valor.

* ```np.abs()```
* ```np.around()```
* ```np.ceil()```
* ```np.exp()```
* ```np.exp2()```
* ```np.fabs()```
* ```np.fix()```
* ```np.floor()```
* ```np.log()```
* ```np.log10()```
* ```np.log1p()```
* ```np.log2()```
* ```np.logaddexp()```
* ```np.logaddexp2()```
* ```np.round()```

In [16]:
numeros = np.array([[1.43, -1, .45, -3.41],
                   [np.inf, -np.inf, np.inf, np.inf],
                   [np.nan, 13.45, 11, 21]])

In [17]:
np.abs(numeros)

array([[ 1.43,  1.  ,  0.45,  3.41],
       [  inf,   inf,   inf,   inf],
       [  nan, 13.45, 11.  , 21.  ]])

In [18]:
np.floor(numeros)

array([[  1.,  -1.,   0.,  -4.],
       [ inf, -inf,  inf,  inf],
       [ nan,  13.,  11.,  21.]])

In [19]:
np.ceil(numeros)

array([[  2.,  -1.,   1.,  -3.],
       [ inf, -inf,  inf,  inf],
       [ nan,  14.,  11.,  21.]])

In [20]:
np.round(numeros)

array([[  1.,  -1.,   0.,  -3.],
       [ inf, -inf,  inf,  inf],
       [ nan,  13.,  11.,  21.]])

## Funciones de evaluación de arreglos.

* ```np.iscomplex()```
* ```np.isfinite()```
* ```np.isin()```
* ```np.isinf()```
* ```np.isnan()```
* ```np.isnat()```
* ```np.isneginf()```
* ```np.isposinf()```
* ```np.isreal()```
* ```np.isscalar()```

In [21]:
np.isfinite(numeros)

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [22]:
np.isnan(numeros)

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [23]:
np.isreal(numeros)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Funciones lógicas.

* ```np.all()```
* ```np.any()```
* ```np.logical_and()```
* ```np.logical_not()```
* ```np.logical_or()```
* ```np.logical_xor()```

In [24]:
booleana = np.array([[0, 1, 1],
                   [1, 0, 1],
                   [1, 1, 1,]], dtype=np.bool_)

In [25]:
booleana

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [26]:
np.any(booleana)

True

In [27]:
np.all(booleana)

False

In [28]:
np.all(booleana[2])

True

In [29]:
np.logical_not(booleana)

array([[ True, False, False],
       [False,  True, False],
       [False, False, False]])

In [30]:
np.logical_or(booleana, True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Funciones polinomiales.

* ```np.poly()```
* ```np.poly1d()```
* ```np.polyadd()```
* ```np.polyder()```
* ```np.polydiv()```
* ```np.polyfit()```
* ```np.polyint()```
* ```np.polymul()```
* ```np.polysub()```
* ```np.polyval()```

$2x^4 + 4x^3 - 3x^2 + 0.5$

In [3]:
ecuacion = np.poly1d([2, 4, -3, 0, 0.5])

$8x^3 + 12x^2 - 6x$

In [4]:
np.polyder(ecuacion)

poly1d([ 8., 12., -6.,  0.])

$0.4x^5 + x^4 -x^3 + 0.5x$

In [5]:
np.polyint(ecuacion)

poly1d([ 0.4,  1. , -1. ,  0. ,  0.5,  0. ])

## Funciones estadísticas.

* ```np.amax()```
* ```np amin()```
* ```np.argmax()```
* ```np.argmin()```
* ```np.average()```
* ```np.correlate()```
* ```np.corrcoef()```
* ```np.count_nonzero()```
* ```np.cov()```
* ```np.cumprod()```
* ```np.cumsum()```
* ```np.histogram()```
* ```np.histogram2d()```
* ```np.histogram_bin_edges()```
* ```np.histogramdd()```
* ```np.max()```
* ```np.mean()```
* ```np.median()```
* ```np.min()```
* ```np.nanargmax()```
* ```np.nanargmin()```
* ```np.nancumprod()```
* ```np.nancumsum()```
* ```np.nanmax()```
* ```np.nanmean()```
* ```np.nanmedian()```
* ```np.nanmin()```
* ```np.nanpercentile()```
* ```np.nanquantile()```
* ```np.nanstd()```
* ```np.nansum()```
* ```np.nanvar()```
* ```np.percentile()```
* ```np.quantile()```
* ```np.std()```
* ```np.var()```

In [31]:
numeros

array([[ 1.43, -1.  ,  0.45, -3.41],
       [  inf,  -inf,   inf,   inf],
       [  nan, 13.45, 11.  , 21.  ]])

In [32]:
np.max(numeros)

nan

In [33]:
np.nanmax(numeros)

inf

In [34]:
np.nanmin(numeros)

-inf

In [35]:
np.nanmean(numeros)

/home/oi/pythonista/lib/python3.7/site-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


nan

In [36]:
np.nanmean(numeros[0])

-0.6325000000000001

In [37]:
np.nanmean(numeros[2])

15.15

In [38]:
np.nanmean(numeros[1])

nan

In [60]:
aleatorios = np.random.randint(100,size=(20))

In [61]:
aleatorios

array([ 1, 99, 81, 43,  5,  1, 80, 82,  1, 91, 65, 87, 23, 28,  8, 36, 89,
        7, 25, 20])

In [62]:
np.histogram(aleatorios)

(array([6, 1, 3, 1, 1, 0, 1, 0, 5, 2]),
 array([ 1. , 10.8, 20.6, 30.4, 40.2, 50. , 59.8, 69.6, 79.4, 89.2, 99. ]))

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2019.</p>