[![imagenes](imagenes/pythonista.png)](https://pythonista.io)

In [1]:
import numpy as np

In [2]:
matriz_1 = np.array([[23.1, 12.5, -11.4],
                  [12.1, -24, 3],
                  [3.4, -2.45, 56]]) 

In [3]:
matriz_1 + 100

array([[123.1 , 112.5 ,  88.6 ],
       [112.1 ,  76.  , 103.  ],
       [103.4 ,  97.55, 156.  ]])

In [4]:
matriz_1 * 4

array([[ 92.4,  50. , -45.6],
       [ 48.4, -96. ,  12. ],
       [ 13.6,  -9.8, 224. ]])

In [5]:
3.42 / matriz_1

array([[ 0.14805195,  0.2736    , -0.3       ],
       [ 0.28264463, -0.1425    ,  1.14      ],
       [ 1.00588235, -1.39591837,  0.06107143]])

In [6]:
matriz_1 / 3.42

array([[ 6.75438596,  3.65497076, -3.33333333],
       [ 3.5380117 , -7.01754386,  0.87719298],
       [ 0.99415205, -0.71637427, 16.37426901]])

In [9]:
matriz_1 > 1

array([[ True,  True, False],
       [ True, False,  True],
       [ True, False,  True]])

In [19]:
matriz_2 = np.array([1, 2, 3])

In [23]:
matriz_3 = np.array([[2], [4], [6]])

In [24]:
matriz_3

array([[2],
       [4],
       [6]])

In [25]:
matriz_1 * matriz_2

array([[ 23.1,  25. , -34.2],
       [ 12.1, -48. ,   9. ],
       [  3.4,  -4.9, 168. ]])

In [26]:
matriz_3 * matriz_1

array([[ 46.2,  25. , -22.8],
       [ 48.4, -96. ,  12. ],
       [ 20.4, -14.7, 336. ]])

In [14]:
matriz_2 ** matriz_1

array([[1.00000000e+00, 5.79261875e+03, 2.00007271e-13],
       [1.00000000e+00, 5.96046448e-08, 2.19700000e+03],
       [1.00000000e+00, 1.83010712e-01, 2.40340925e+62]])

In [17]:
 matriz_1.transpose()

array([[ 23.1 ,  12.1 ,   3.4 ],
       [ 12.5 , -24.  ,  -2.45],
       [-11.4 ,   3.  ,  56.  ]])

In [18]:
matriz_1.dot(matriz_2)

array([-100.1,    3.1,  726.5])

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2018.</p>