[![imagenes/pythonista.png](imagenes/pythonista.png)](https://pythonista.io)

Numpy es el componente de Scipy que contiene las herramientas básicas de cálculo numérico, generación de números aleatorios, estadística básica, trigonometría, operaciones matriciales y a algebra lineal; entre otras, las cuales son utilizadas intensivamente por el resto de las bibliotecas.

Su propia biblioteca de recursos es muy extensa y cubre gran cantidad de herramientas.

A continuación se presentarán algunas de ellas.

## Rangos numéricos.

Numpyu incluye alguinas funciones que generan una sucesion de números en un rango específico. Una de estar funciones es *np.arange()*. Sin embargo, existen otras como *np.linstep()* y *np.logspace()*.

### La función *np.linspace()*.

Esta función creará una secuencia de números dentro de un rango dado que corresponde segmentos, incluyendo el inicio y el final.

In [5]:
import numpy as np

In [9]:
np.linspace(0, 7)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ,
       2.14285714, 2.28571429, 2.42857143, 2.57142857, 2.71428571,
       2.85714286, 3.        , 3.14285714, 3.28571429, 3.42857143,
       3.57142857, 3.71428571, 3.85714286, 4.        , 4.14285714,
       4.28571429, 4.42857143, 4.57142857, 4.71428571, 4.85714286,
       5.        , 5.14285714, 5.28571429, 5.42857143, 5.57142857,
       5.71428571, 5.85714286, 6.        , 6.14285714, 6.28571429,
       6.42857143, 6.57142857, 6.71428571, 6.85714286, 7.        ])

### La función *np.logspace()*.

Esta función creará una secuencia de números en una sucesion logarítmica. La base por defecto es 10.

In [10]:
np.logspace(5, 7, num=10)

array([  100000.        ,   166810.05372001,   278255.94022071,
         464158.88336128,   774263.68268113,  1291549.66501488,
        2154434.69003188,  3593813.66380463,  5994842.50318941,
       10000000.        ])

## El paquete *numpy.linalg*.

La biblioteca especialziada en operaciones de algebra lineal de Numpy es *numpy.linalg*.

El estudio de todas las funciones contenodas en este paquete están fuera de los alcances de este curso, pero se ejemplificarán las funciones.

* numpy.linalg.det()
* numpy.linalg.det()

In [11]:
import numpy.linalg

In [12]:
help(numpy.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

### Cálculo del determinate de una matriz mediante *numpy.linalg.det()*.



**Ejemplo:**

Se calculará el determinante de la matriz:

$$ \det\begin{vmatrix}0&1&2\\3&4&5\\6&7&8\end{vmatrix}$$

El cálculo del determinante es el siguiente:

$$ ((0 * 4 * 8) + (1 * 5 * 6) + (2 * 3 * 7)) - ((6 * 4 * 2) + (7 * 5 * 0) + (8 * 3* 1)) = 0$$

In [14]:
matriz = np.arange(9).reshape(3,3)

In [19]:
matriz

array([[1, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
numpy.linalg.det(matriz)

-2.999999999999999

In [17]:
matriz[0,0] = 1

### Soluciones de ecuaciones lineales con la función *np.linalg.solve()*.

Un sistema de ecuaciones lineales coresponde un conjunto de ecuaciones de la forma:

$$
a_{11}x_1 + a_{12}x_2 + \cdots a_{1n}x_n = y_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots a_{2n}x_n = y_2\\
\vdots\\
a_{m1}x_1 + a_{m2}x_2 + \cdots a_{mn}x_n = y_m
$$

Lo cual puede ser expresado de forma matricial.

$$ 
\begin{bmatrix}a_{11}\\a_{21}\\ \vdots\\ a_{m1}\end{bmatrix}x_1 + \begin{bmatrix}a_{12}\\a_{22}\\ \vdots\\ a_{m2}\end{bmatrix}x_2 + \cdots \begin{bmatrix}a_{m1}\\a_{m2}\\ \vdots\\ a_{mn}\end{bmatrix}x_n = \begin{bmatrix}y_{1}\\y_{2}\\ \vdots\\ y_{m}\end{bmatrix}
$$

Existen múltiples métodos para calcular los valores $x_1, x_2 \cdots x_n$ que cumplan con el sistema siempre que $m = n$.

Numpy cuenta con la función *np.linalg.solve()*, la cual puede calcular la solución de un sistema de ecuaciones lineales al expresarse como un par de matrices de la siguiente foma:

$$ 
\begin{bmatrix}a_{11}&a_{12}&\cdots&a_{1n}\\a_{21}&a_{22}&\cdots&a_{2n}\\ \vdots\\ a_{n1}&a_{n2}&\cdots&a_{nn}\end{bmatrix}= \begin{bmatrix}y_{1}\\y_{2}\\ \vdots\\ y_{n}\end{bmatrix}
$$

La función *numpy.linagl.solve()* permite resolver sistemas de ecuaciones lineales ingresando un arreglo de dimensiones (n, n) como primer argumente y otro con dimensión (n) como segundo argumento. 

**Ejemplo:**

Para resolver el sistema de ecuaciones:

$$
2x_1 + 5x_2 - 3x_3 = 22.2 \\
11x_1 - 4x_2 + 22x_3 = 11.6 \\
54x_1 + 1x_2 + 19x_3 = -40.1 \\
$$

Se realiza lo siguiente:

In [21]:
a = np.array([[2, 5, -3],
              [11, -4, 22],
              [54, 1, 19]])

In [22]:
a.shape

(3, 3)

In [23]:
y = np.array([22.2, 11.6, -40.1])

In [24]:
y.shape

(3,)

In [25]:
np.linalg.solve(a,y)

array([-1.80243902,  6.7549776 ,  2.65666999])

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2018.</p>